Update admlb

diff --git a/admlb b/admlb
--- a/admlb
+++ b/admlb
@@ -1,14 +1,15 @@
 #!/bin/bash
 
 if [[ ${CONFIG_FILE_URL} ]]; then
-    echo "Detected CONFIG_FILE_URL, Downloading..."
-    curl -o config.env -s $CONFIG_FILE_URL && echo "Done"
+    printf "Detected CONFIG_FILE_URL, Downloading..."
+    curl -o config.env -s $CONFIG_FILE_URL &&
+    printf "DONE!"
 else
-    echo "CONFIG_FILE_URL var not provided!"
+    printf "CONFIG_FILE_URL var not provided!"
 fi
 
 if [[ -f config.env ]]; then
-    echo "Loading... UPSTREAM_REPO and UPSTREAM_BRANCH from config.env"
+    printf "Loading... UPSTREAM_REPO and UPSTREAM_BRANCH from config.env"
     export $(echo "from os import environ
 from dotenv import load_dotenv
 
@@ -18,18 +19,18 @@ UPSTREAM_REPO = environ.get('UPSTREAM_REPO')
 UPSTREAM_BRANCH = environ.get('UPSTREAM_BRANCH')
 
 print(f'UPSTREAM_REPO={UPSTREAM_REPO}')
-print(f'UPSTREAM_BRANCH={UPSTREAM_BRANCH}')" | python3) && echo "Done"
+print(f'UPSTREAM_BRANCH={UPSTREAM_BRANCH}')" | python3) &&
+    printf "DONE!"
 else
-    echo "Config.env file missing! Exiting now"
-    exit
+    printf "Config.env file missing! Exiting now" || exit
 fi
 
 if [[ ${UPSTREAM_REPO} && ${UPSTREAM_BRANCH} ]]; then
-    echo "Detected UPSTREAM_REPO and UPSTREAM_BRANCH"
+    printf "Detected UPSTREAM_REPO and UPSTREAM_BRANCH"
 else
     UPSTREAM_REPO=https://github.com/ahadz-git/mirror-leech-telegram-bot
     UPSTREAM_BRANCH=h-code
-    echo "UPSTREAM_REPO or UPSTREAM_BRANCH missing! Using default once"
+    printf "UPSTREAM_REPO or UPSTREAM_BRANCH missing! Using default once"
 fi
 
 [ -d .git ] && rm -rf .git
